apiVersion: v2
name: funcx
description: FuncX Register and Run Functions Anywhere

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.3.1

dependencies:
  - name: postgresql
    version: 9.1.4
    repository: https://charts.bitnami.com/bitnami
    condition: services.postgres.enabled
    primary:
      extendedConfiguration: |
        tcp_keepalives_idle = 60
        tcp_keepalives_interval = 20
        tcp_keepalives_count = 10
  - name: redis
    version: 10.7.*
    repository: https://charts.bitnami.com/bitnami
    condition: services.redis.enabled
  - name: rabbitmq
    version: 8.11.6
    repository: https://charts.bitnami.com/bitnami
    condition: services.rabbitmq.enabled
  - name: funcx_endpoint
    version: 0.2.*
    repository: http://funcx.org/funcx-helm-charts
    condition: endpoint.enabled


