---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-funcx-web-service
spec:
  ports:
   - port: 8000
     targetPort: 5000
     name: "tcp"
     protocol: TCP
  selector:
    app: {{ .Release.Name }}-funcx-web-service
  type: ClusterIP