apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-funcx-websocket-service
spec:
  replicas: {{ .Values.websocketService.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-funcx-websocket-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-funcx-websocket-service
    spec:
      {{- if .Values.storage.s3ServiceAccount }}
      serviceAccountName: {{- .Values.storage.s3ServiceAccount }}
      securityContext:
        fsGroup: 1000
      {{- end }}
      containers:
      - name: {{ .Release.Name }}-funcx-websocket-service
        image: {{ .Values.websocketService.image }}:{{ .Values.websocketService.tag }}
        imagePullPolicy: {{ .Values.websocketService.pullPolicy }}
        env:
        - name: REDIS_HOST
    {{- if .Values.services.redis.enabled }}
          value: ""
    {{- else }}
          value: "{{  .Values.services.redis.externalHost }}"
    {{- end }}
        - name: REDIS_PORT
    {{- if .Values.services.redis.enabled }}
          value: "6379"
    {{- else }}
          value: "{{  .Values.services.redis.externalPort }}"
    {{- end }}
        - name: RABBITMQ_URI
    {{- if .Values.services.rabbitmq.enabled }}
          value: ""
    {{- else }}
          value: "{{  .Values.services.rabbitmq.externalURI }}"
    {{- end }}
        - name: WEB_SERVICE_URI
          value: "http://{{ .Release.Name }}-funcx-web-service:8000"

    {{- if  .Values.storage.awsSecrets }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.storage.awsSecrets }}
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.storage.awsSecrets }}
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.storage.awsSecrets }}
              key: AWS_SESSION_TOKEN
    {{- end }}

    {{- if  .Values.storage.s3Bucket }}
        - name: FUNCX_S3_BUCKET_NAME
          value: "{{ .Values.storage.s3Bucket }}"
    {{- end }}
    {{- if  .Values.storage.redisThreshold }}
        - name: FUNCX_REDIS_STORAGE_THRESHOLD
          value: "{{ .Values.storage.redisThreshold }}"
    {{- end }}

        ports:
          - containerPort: 6000
